version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mlflow_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mlflow_db
      MYSQL_USER: mlflow_user
      MYSQL_PASSWORD: mlflow_pass
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    container_name: Minio
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  jupyterlab:
    build: .
    container_name: jupyterlab
    volumes:
      - .:/work
    ports:
      - "8888:8888"
    environment:
      MLFLOW_TRACKING_URI: http://10.43.101.205:5000
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: supersecret
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token=''
  
  inference_api:
    build:
      context: ./inference_api
      dockerfile: Dockerfile  # Esto es opcional si el archivo se llama Dockerfile
    container_name: inference_api
    ports:
      - "8000:8000"

volumes:
  mysql_data:
  minio_data:



